name: noi_2213025033
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  pie_chart: ^5.4.0
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/gambar_hal1.png
    - assets/images/newtaskimage.png
    - assets/images/logo.png

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter_bold.ttf
        - asset: assets/fonts/inter_extralight.ttf
        - asset: assets/fonts/inter_semibold.ttf
